### ISSUE TITLE
Missing qualified binutils in 11.4

### ISSUE THREAD

**Issue by MrDOS** [MrDOS/freebsd-cross-build#2]
I didn't install the full `llvm16` package in the 11.4 image, and didn't symlink its binutils equivalents to qualified names. Specifically, the 9.3 image has qualified instances of:

* addr2line
* ar
* as
* c++
* c++filt
* cpp
* g++
* gcc
* gcc-4.2.4
* gccbug
* gcov
* gprof
* ld
* nm
* objcopy
* objdump
* ranlib
* readelf
* size
* strings
* strip

...whereas the 11.4 images only have qualified names for:

* c++
* cc
* clang
* clang++
* clang-cpp
* cpp
* ld

I would say the omission of `cc` from the 9.3 image was an oversight. And some GCC-specific tools (`gcc`, `gcc-4.2.4`, `gccbug`) obviously won't be making a reappearance in the 11.4 image. But I should add qualified, compatible versions of all of the rest, and maybe expand the `settarget` script to provide the tools by unqualified names, too.

**Comment by michael-o** [comment]
@MrDOS Did you find the time to address this issue?

**Comment by byteit101** [comment]
What would I need to do to add them back in? I'm currently in the middle of trying to cross compile native libraries for a wide matrix of machines, and the 9.x builds work well, but using 11.4 for arm I had to disable: https://github.com/byteit101/subspawn/commit/bc4aad7811ef03fecea2129fe61d46198f4f7446

edit: I just need a qualified `strip` personally

**Comment by MrDOS** [comment]
Thanks for the encouragement, guys.

To add the tools back in, I had to install the full LLVM package (which includes their cross-platform binutils), confirm that the tools of interest worked without additional `--target` or `--arch` flags (and therefore did not require additional wrapper scripts), then add symlinks in all the right places. See the commit I just made for the full gory details.

Because the commit message indicated that it closed this issue, GitHub consequently closed the issue as soon as I pushed it. I'm still rebuilding the images; I'll comment again here in a few minutes once they're built and pushed to Docker Hub.

**Comment by michael-o** [comment]
> Thanks for the encouragement, guys.
> 
> To add the tools back in, I had to install the full LLVM package (which includes their cross-platform binutils), confirm that the tools of interest worked without additional `--target` or `--arch` flags (and therefore did not require additional wrapper scripts), then add symlinks in all the right places. See the commit I just made for the full gory details.
> 
> Because the commit message indicated that it closed this issue, GitHub consequently closed the issue as soon as I pushed it. I'm still rebuilding the images; I'll comment again here in a few minutes once they're built and pushed to Docker Hub.

Thanks, your hard work is appreciated.

**Comment by MrDOS** [comment]
New amd64 and arm64 container images are pushed up. Assuming I haven't royally screwed up something _else_ this time, you should be good to go. Please do let me know how it goes!

**Comment by byteit101** [comment]
Thanks! I need to find some way to test them now, but at least the build itself is now green:
https://github.com/byteit101/subspawn/actions/runs/9201531705

image for future reference once that run is deleted:
![Screenshot 2024-05-22 at 23-32-19 Spell el not le and add ppc64 · byteit101_subspawn@527b0c0](https://github.com/MrDOS/freebsd-cross-build/assets/577344/88e32f64-376e-4c67-a544-4300778401c0)

**Comment by MrDOS** [comment]
I typically throw a few cents at the problem and use [an EC2 spot instance](https://aws.amazon.com/ec2/spot/). A t4g.micro usually has plenty of resources, and while the FreeBSD AMIs take a bit longer to spin up than their Amazon Linux equivalents, they're still up and ready to use long before I can remember how to use virt-manager.

**Comment by michael-o** [comment]
Will try next week....
